name: Kaitai Struct Release
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Install kaitai-struct-compiler
        run: |
          curl -LO https://github.com/kaitai-io/kaitai_struct_compiler/releases/download/0.10/kaitai-struct-compiler_0.10_all.deb
          sudo apt-get install ./kaitai-struct-compiler_0.10_all.deb
          kaitai-struct-compiler --version
      - name: Run kaitai-struct-compiler
        run: |
          kaitai-struct-compiler --target all --outdir ./osu_db_kaitai *.ksy
          zip -r ./osu_db_kaitai.zip osu_db_kaitai
          tar -czvf ./osu_db_kaitai.tar.gz osu_db_kaitai
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            osu_db_kaitai.zip
            osu_db_kaitai.tar.gz
